#!/usr/bin/env bash

# Check if oh-my-zsh is installed
OMZDIR="$HOME/.oh-my-zsh"
if [ ! -d "$OMZDIR" ]; then
  echo 'Installing oh-my-zsh'
  /bin/sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
fi

# Check if starship is installed
if ! [ -x "$(command -v starship)" ]; then
  echo 'Installing starship'
  /bin/sh -c "$(curl -fsSL https://starship.rs/install.sh)"
fi
