[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "ResetFontSize"
key = "Key0"
mods = "Control"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Equals"
mods = "Control"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Control"

[colors.bright]
black = "#75715e"
blue = "#66d9ef"
cyan = "#a1efe4"
green = "#a6e22e"
magenta = "#ae81ff"
red = "#f92672"
white = "#f9f8f5"
yellow = "#f4bf75"

[colors.cursor]
cursor = "#f8f8f2"
text = "#272822"

[colors.normal]
black = "#272822"
blue = "#66d9ef"
cyan = "#a1efe4"
green = "#a6e22e"
magenta = "#ae81ff"
red = "#f92672"
white = "#f8f8f2"
yellow = "#f4bf75"

[colors.primary]
background = "#272822"
foreground = "#f8f8f2"

[cursor.style]
blinking = "Never"

[font]
size = 11.0

[font.glyph_offset]
x = 0
y = 0

[font.bold]
family = "Inconsolata Nerd Font"
style = "Bold"

[font.italic]
family = "monospace"
style = "Italic"

[font.normal]
family = "Inconsolata Nerd Font"
style = "Regular"

[font.offset]
x = 0
y = 0

[window]
dynamic_title = true

[env]
TERM = "xterm-256color"

[window.padding]
x = 2
y = 2

[keyboard]
